// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }


// import "./globals.css";
// import Link from "next/link";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }


// import "./globals.css";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }

// import "./globals.css";

// export const metadata = {
//   title: "Raghav Portfolio",
//   description: "Raghav's Portfolio",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }



// import "./globals.css";

// export const metadata = {
//   title: "Raghav Portfolio",
//   description: "My personal portfolio",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }

import "./globals.css";

export const metadata = {
  title: "Raghav Portfolio",
  description: "Personal Portfolio of Raghav",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* PAGE CONTENT */}
        {children}

        {/* FOOTER */}
        <footer className="global-footer">
  © {new Date().getFullYear()} Raghav Ventures. All Rights Reserved
</footer>

      </body>
    </html>
  );
}

